#!/usr/bin/env bash
# Prints the Homebrew formula for one release.
#
# Usage: homebrew-formula.sh <version> <path-to-SHA256SUMS>
set -euo pipefail

version="$1"
sums="$2"

sha() {
  local hash
  hash=$(grep " getcmd-$version-$1.tar.gz\$" "$sums" | cut -d' ' -f1)
  [ -n "$hash" ] || { echo "no checksum for $1 in $sums" >&2; exit 1; }
  echo "$hash"
}

cat << EOF
# Generated by .github/scripts/homebrew-formula.sh for getcmd v$version. Do not edit by hand.
class Getcmd < Formula
  desc "Command safety for AI coding agents"
  homepage "https://getcmd.com"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/getCMD-com/getcmd/releases/download/v$version/getcmd-$version-osx-arm64.tar.gz"
      sha256 "$(sha osx-arm64)"
    end
    on_intel do
      url "https://github.com/getCMD-com/getcmd/releases/download/v$version/getcmd-$version-osx-x64.tar.gz"
      sha256 "$(sha osx-x64)"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getCMD-com/getcmd/releases/download/v$version/getcmd-$version-linux-arm64.tar.gz"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "https://github.com/getCMD-com/getcmd/releases/download/v$version/getcmd-$version-linux-x64.tar.gz"
      sha256 "$(sha linux-x64)"
    end
  end

  def install
    bin.install "getcmd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/getcmd --version")
  end
end
EOF
