# Generated by .github/scripts/homebrew-formula.sh for getcmd v0.1.0-alpha.3. Do not edit by hand.
class Getcmd < Formula
  desc "Command safety for AI coding agents"
  homepage "https://getcmd.com"
  version "0.1.0-alpha.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/getCMD-com/getcmd/releases/download/v0.1.0-alpha.3/getcmd-0.1.0-alpha.3-osx-arm64.tar.gz"
      sha256 "b314c18ffaca727e4f3071d728c9632ce754784db9f0e453cdb5a3d5f60c5ae7"
    end
    on_intel do
      url "https://github.com/getCMD-com/getcmd/releases/download/v0.1.0-alpha.3/getcmd-0.1.0-alpha.3-osx-x64.tar.gz"
      sha256 "9075719e496f2481151750485ed3e9d8a8808887ccc23d5475dad2a31ff0a977"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getCMD-com/getcmd/releases/download/v0.1.0-alpha.3/getcmd-0.1.0-alpha.3-linux-arm64.tar.gz"
      sha256 "df1c68396cc7f535f4eee517a9e320426cf3d78f17cb18ba01a139ee90548539"
    end
    on_intel do
      url "https://github.com/getCMD-com/getcmd/releases/download/v0.1.0-alpha.3/getcmd-0.1.0-alpha.3-linux-x64.tar.gz"
      sha256 "3fc644d1809a5ba6ba40effa5472f472a51c430038f6c6d6751449a74315225d"
    end
  end

  def install
    bin.install "getcmd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/getcmd --version")
  end
end
