# Generated by .github/scripts/homebrew-formula.sh for getcmd v0.1.0-alpha.2. Do not edit by hand.
class Getcmd < Formula
  desc "Command safety for AI coding agents"
  homepage "https://getcmd.com"
  version "0.1.0-alpha.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/getCMD-com/getcmd/releases/download/v0.1.0-alpha.2/getcmd-0.1.0-alpha.2-osx-arm64.tar.gz"
      sha256 "0d59d9d643df76b547af374c893c3a04e321e95d31b018cc3b3f8b8fd1b78e15"
    end
    on_intel do
      url "https://github.com/getCMD-com/getcmd/releases/download/v0.1.0-alpha.2/getcmd-0.1.0-alpha.2-osx-x64.tar.gz"
      sha256 "aaf6c846faad43891ad3955a3199aa957248b2284ff43a9d94916bdefdeb1799"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getCMD-com/getcmd/releases/download/v0.1.0-alpha.2/getcmd-0.1.0-alpha.2-linux-arm64.tar.gz"
      sha256 "1a9b00b99d1a8a2ca3c42395edafa26b16d3204b467faefa4886d454acc25a44"
    end
    on_intel do
      url "https://github.com/getCMD-com/getcmd/releases/download/v0.1.0-alpha.2/getcmd-0.1.0-alpha.2-linux-x64.tar.gz"
      sha256 "eecb122f6ed6c664016594e566cfcc16e2274b391e77d2339c0402c15a505a6b"
    end
  end

  def install
    bin.install "getcmd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/getcmd --version")
  end
end
